[package]
name = "reflections"
version = "0.1.0"
edition = "2024"

[dependencies]
# bevy_ecs = { version = "0.18.0", features = ["multi_threaded"] }
glam = "0.32.0"
raylib = { version = "5.5.1", features = ["wayland", "imgui"] }
# imgui = "0.12.0"
# raylib = { version = "5.5.1", features = ["imgui"] }
